<<<<<<< HEAD
spring.application.name=fsad-project
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/fsad_db
=======
spring.application.name=DynamicOnlineEstemxaminationAndResultProcessingSystem
spring.datasource.url=jdbc:mysql://localhost:3306/examinationDB
>>>>>>> 93b0578dd1b31175d9773aca7830fd8bfe554f45
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
<<<<<<< HEAD
=======
spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp
>>>>>>> 93b0578dd1b31175d9773aca7830fd8bfe554f45
